/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-03-17 01:08:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.proupdate;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import com.tick.bean.BookticketBean;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1741868033627L));
    _jspx_dependants.put("jar:file:/C:/Action/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664424678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tick.bean.BookticketBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>更新訂票</title>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: \"Open Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", Helvetica, Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #success_message {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #datepicker {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1000000;\r\n");
      out.write("        }\r\n");
      out.write("        .ud{\r\n");
      out.write("        pointer-events: none;\r\n");
      out.write("        background: #fff !important;\r\n");
      out.write("        }\r\n");
      out.write("        html{\r\n");
      out.write("        font-size:16px ;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("    <!--[if lt IE 9]>       \r\n");
      out.write("  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>       \r\n");
      out.write("  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>     \r\n");
      out.write("  <![endif]-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\"\r\n");
      out.write("        integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\"\r\n");
      out.write("        crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"ui/jquery-ui-1.14.1.custom/jquery-ui.css\">\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"/ui/jquery-ui-1.14.1.custom/jquery-ui.js\"> -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.17.2/dist/sweetalert2.min.css\">\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <form class=\"well form-horizontal\" action=\"Updatea\" method=\"post\" id=\"contact_form\">\r\n");
      out.write("            <fieldset>\r\n");
      out.write("\r\n");
      out.write("                <!-- Form Name -->\r\n");
      out.write("                <legend>修改訂票</legend>\r\n");
      out.write("\r\n");
      out.write("                <!-- Text input-->\r\n");
      out.write("				<input name=\"tickid\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.tickid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">訂單編號</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-clipboard-list\"></i></span>\r\n");
      out.write("                            <input name=\"orderid\" placeholder=\"訂單編號\" class=\"form-control ud\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.orderid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Text input-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">會員</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-user\"></i></span>\r\n");
      out.write("                            <input name=\"userid\" placeholder=\"會員\" class=\"form-control ud\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.userid }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Text input-->\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">日期</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-calendar-days\"></i></span>\r\n");
      out.write("                            <input type=\"text\" id=\"datepicker\" class=\"form-control\" placeholder=\"日期\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.startdate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">場次</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-clock\"></i></span>\r\n");
      out.write("                            <select name=\"starttime\" class=\"form-control selectpicker\" id=\"time\">\r\n");
      out.write("                                <option value=\" \">場次</option>\r\n");
      out.write("                                \r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Text input-->\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">廳</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-house\"></i></span>\r\n");
      out.write("                        	 <select name=\"hallid\" class=\"form-control selectpicker\" id=\"halls\">\r\n");
      out.write("                                <option value=\"\">廳</option>\r\n");
      out.write("                                \r\n");
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">座位</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-chair\"></i></span>\r\n");
      out.write("                            <select name=\"Seatid\" class=\"form-control selectpicker\" id=\"seat\">\r\n");
      out.write("                                <option value=\"\">座位</option>\r\n");
      out.write("                                \r\n");
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Text input-->\r\n");
      out.write(" 				<div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">票種</label>\r\n");
      out.write("                    <div class=\"col-md-4 selectContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-ticket\"></i></span>\r\n");
      out.write("                            <select name=\"tickettypeid\" class=\"form-control selectpicker\" id=\"type\">\r\n");
      out.write("                                <option value=\" \">票種</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <!-- Text input-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">電影名稱</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-film\"></i></span>\r\n");
      out.write("                            \r\n");
      out.write("                            <select name=\"movieid\" class=\"form-control selectpicker\" id=\"moviename\">\r\n");
      out.write("                                <option value=\" \">電影</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Select Basic -->\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">單價</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa-solid fa-coins\"></i></span>\r\n");
      out.write("                            <input name=\"onemoney\" placeholder=\"單價\" class=\"form-control\" type=\"text\" id=\"money\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Text input-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\">是否付款</label>\r\n");
      out.write("                    <div class=\"col-md-4 inputGroupContainer\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                        \r\n");
      out.write("                         \r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-home\"></i></span>\r\n");
      out.write("                            <select name=\"payout\" class=\"form-control selectpicker\">\r\n");
      out.write("                                <option value=\" \">是否付款</option>\r\n");
      out.write("                                <option value=\"Y\" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(">已付</option>\r\n");
      out.write("                                <option value=\"N\" ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(">未付</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Button -->\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-md-4 control-label\"></label>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <button  class=\"btn btn-warning\" id=\"seed\">Send <span\r\n");
      out.write("                                class=\"glyphicon glyphicon-send\"></span></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </fieldset>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("   <!-- /.container -->\r\n");
      out.write("    <!-- <script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script> -->\r\n");
      out.write("    <!-- <script src=\"js/bootstrap.min.js\"></script> -->\r\n");
      out.write("    <!-- <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("    <script src=\"https//cdnjs.cloudflare.com/ajax/libs/validate.js/0.13.1/validate.min.js\"></script> -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("    <script src=\"ui/jquery-ui-1.14.1.custom/jquery-ui.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.17.2/dist/sweetalert2.all.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("    $(function () {\r\n");
      out.write("    	//Swal.fire(\"SweetAlert2 is working!\");\r\n");
      out.write("    const $myForm=	$('#contact_form').on(\"submit\",function(e){\r\n");
      out.write("    		e.preventDefault();\r\n");
      out.write("    		Swal.fire({\r\n");
      out.write("    			  title: \"要進行修改嗎?\",\r\n");
      out.write("    			  icon: \"warning\",\r\n");
      out.write("    			  showDenyButton: true,\r\n");
      out.write("    			  showCancelButton: true,\r\n");
      out.write("    			  confirmButtonText: \"修改\",\r\n");
      out.write("    			  denyButtonText: `我在想想`,\r\n");
      out.write("    			  didOpen: () => {\r\n");
      out.write("    				    $('#datepicker').prop('disabled', true) // 禁用 datepicker\r\n");
      out.write("    				      .css({\r\n");
      out.write("    				        'background-color': '#999999',  // 設定與其他輸入框相同的背景色\r\n");
      out.write("    				        'color': '#000',  // 讓文字顏色一致\r\n");
      out.write("    				        'cursor': 'not-allowed',\r\n");
      out.write("    				        'border':'1px solid #7d7d7d'// 讓滑鼠變成禁止點擊的樣式\r\n");
      out.write("    				      });\r\n");
      out.write("    				  },\r\n");
      out.write("    				  didClose: () => {\r\n");
      out.write("    				    $('#datepicker').prop('disabled', false) // 恢復可用\r\n");
      out.write("    				      .css({\r\n");
      out.write("    				        'background-color': '', // 恢復原本的樣式\r\n");
      out.write("    				        'color': '',\r\n");
      out.write("    				        'cursor': '',\r\n");
      out.write("    				        'border':''\r\n");
      out.write("    				      });\r\n");
      out.write("    				  }\r\n");
      out.write("                 // buttonsStyling: false\r\n");
      out.write("    			}).then((result) => {\r\n");
      out.write("    			  \r\n");
      out.write("    			  if (result.isConfirmed) {\r\n");
      out.write("    			    //Swal.fire(\"Saved!\", \"\", \"success\",customClass: {\r\n");
      out.write("                    //    confirmButton: 'btn btn-success'\r\n");
      out.write("                  //  })\r\n");
      out.write("    		        Swal.fire({\r\n");
      out.write("                                icon: 'success',\r\n");
      out.write("                                title: '修改成功!!',\r\n");
      out.write("                                text: '',\r\n");
      out.write("                                customClass: {\r\n");
      out.write("                                    confirmButton: 'btn btn-success'\r\n");
      out.write("                                    \r\n");
      out.write("                                }\r\n");
      out.write("                            });\r\n");
      out.write("    		        setTimeout(function() {\r\n");
      out.write("    		        	$myForm[0].submit()\r\n");
      out.write("    		          }, 2000); // submit the DOM form\r\n");
      out.write("    		       \r\n");
      out.write("    			  } else if (result.isDenied) {\r\n");
      out.write("    			    Swal.fire(\"Changes are not saved\", \"\", \"info\");\r\n");
      out.write("    			  }\r\n");
      out.write("    			});\r\n");
      out.write("    	})\r\n");
      out.write("    	///////////////////////////////////////\r\n");
      out.write("    	let urlhttp='http://localhost:8080/project/';\r\n");
      out.write("    	//console.log(urlhttp)\r\n");
      out.write("/////////////////////////////////////////////////////////////    	\r\n");
      out.write("    	$(\"#datepicker\").datepicker({ dateFormat: 'yy-mm-dd'});\r\n");
      out.write("        $(\"#from-datepicker\").on(\"change\", function () {\r\n");
      out.write("            var fromdate = $(this).val();\r\n");
      out.write("            alert(fromdate);\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        //點選日期改時間\r\n");
      out.write("        let urltime = urlhttp+'findshowtime';\r\n");
      out.write("        $(\"#datepicker\").on(\"change\",function () {\r\n");
      out.write("        	let selectdate=$(\"#datepicker\").val();\r\n");
      out.write("        	$(\"#time\").empty();\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: urltime,\r\n");
      out.write("                data:{startdate:selectdate},\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                success: function (respones) {\r\n");
      out.write("                	$('#time').append(`<option value=\"\">場次</option>`);\r\n");
      out.write("					$.each(respones,function(i,e){\r\n");
      out.write("						\r\n");
      out.write("						$('#time').append(`<option value=\"${e.showtimeid}\">${e.starttime}</option>`)\r\n");
      out.write("					})\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("    });\r\n");
      out.write("        //ready畫面加載預設時間\r\n");
      out.write("        \r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("        	let selectdate=$(\"#datepicker\").val();\r\n");
      out.write("        	$(\"#time\").empty();\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: urltime,\r\n");
      out.write("                data:{startdate:selectdate},\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                success: function (respones) {\r\n");
      out.write("                	$('#time').append(`<option value=\"\">場次</option>`);\r\n");
      out.write("					$.each(respones,function(i,e){\r\n");
      out.write("						let tickshow='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.showtimeid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("						//console.log(tickshow)\r\n");
      out.write("						let selectshow = (tickshow==e.showtimeid)?'selected':''\r\n");
      out.write("						$('#time').append(`<option value=\"${e.showtimeid}\" ${selectshow} >${e.starttime}</option>`)\r\n");
      out.write("					})\r\n");
      out.write("                },\r\n");
      out.write("                error:function(){console.log('time')}\r\n");
      out.write("            })\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        //\r\n");
      out.write("        let urlhall = urlhttp+'findhalls';\r\n");
      out.write("        \r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: urlhall,\r\n");
      out.write("                    dataType: 'json',\r\n");
      out.write("                    type: 'GET',\r\n");
      out.write("                    success: function (respones) {\r\n");
      out.write("						$.each(respones,function(i,e){\r\n");
      out.write("                    	\r\n");
      out.write("						    let tickhall = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.hallid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" // 直接輸出數值\r\n");
      out.write("		                    let selectshows = (tickhall == e.hallid) ? 'selected' : '';\r\n");
      out.write("		                    \r\n");
      out.write("		                    //console.log(e.hallid);\r\n");
      out.write("							$('#halls').append(`<option value=\"${e.hallid}\" ${selectshows}>${e.hallid}</option>`)\r\n");
      out.write("							$('#moviename').empty();\r\n");
      out.write("        	\r\n");
      out.write("        	\r\n");
      out.write("        	//console.log(hall)\r\n");
      out.write("        	\r\n");
      out.write("					})\r\n");
      out.write("					let hall=$(\"#halls\").val();\r\n");
      out.write("					/////\r\n");
      out.write("					urlname=urlhttp+\"findmoviename\"\r\n");
      out.write("        	$.ajax({\r\n");
      out.write("                url: urlname,\r\n");
      out.write("                data:{hallid:hall},\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                success: function (respones) {\r\n");
      out.write("                	console.log(respones)\r\n");
      out.write("                	$('#moviename').empty();\r\n");
      out.write("                	$.each(respones,function(i,e){\r\n");
      out.write("                		//$('#moviename').append(`<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.movieid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.moviename}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>`)\r\n");
      out.write("						//$('#moviename').val(e.moviename)\r\n");
      out.write("						$('#moviename').append(`<option value=\"${e.movieid}\">${e.moviename}</option>`)\r\n");
      out.write("						\r\n");
      out.write("				})\r\n");
      out.write("					\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("				////	\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("    });\r\n");
      out.write("        let urlseat = urlhttp+'findseatbytimehall'\r\n");
      out.write("        $(\"#halls\").on(\"change\",function(){\r\n");
      out.write("        	let selecttime=$(\"#time\").val();\r\n");
      out.write("        	\r\n");
      out.write("        	let selecthall=$(\"#halls\").val();\r\n");
      out.write("        	//console.log(selecthall)\r\n");
      out.write("        	$(\"#seat\").empty();\r\n");
      out.write("        	let soldSeats=[];\r\n");
      out.write("        	$.ajax({\r\n");
      out.write("                url: urlseat,\r\n");
      out.write("                data:{showtimeid:selecttime,hallid:selecthall},\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                success: function (respones) {\r\n");
      out.write("					$.each(respones,function(i,e){\r\n");
      out.write("						\r\n");
      out.write("						soldSeats.push(e.seatid);\r\n");
      out.write("					})\r\n");
      out.write("						let allSeats = [];\r\n");
      out.write("        // 生成所有座位 (假設 5 排，每排 5 個座位)\r\n");
      out.write("        for (let row of [\"A\", \"B\", \"C\", \"D\", \"E\"]) {\r\n");
      out.write("            for (let col = 1; col <= 10; col++) {\r\n");
      out.write("                allSeats.push(row + col);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        // 取得 <select> 元素\r\n");
      out.write("        let select = document.getElementById(\"seat\");\r\n");
      out.write("        // 過濾出尚未售出的座位\r\n");
      out.write("        let availableSeats = allSeats.filter(seat => !soldSeats.includes(seat));\r\n");
      out.write("        // 生成 <option> 並添加到 <select>\r\n");
      out.write("        availableSeats.forEach(seat => {\r\n");
      out.write("            //let option = document.createElement(\"option\");\r\n");
      out.write("            //option.value = seat;\r\n");
      out.write("           // option.textContent = seat;\r\n");
      out.write("            //select.appendChild(option);\r\n");
      out.write("            $('#seat').append(`<option value=\"${seat}\">${seat}</option>`)\r\n");
      out.write("			\r\n");
      out.write("        })\r\n");
      out.write("            	}\r\n");
      out.write("        	})\r\n");
      out.write("        })\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("        	let selecttime=$(\"#time\").val();\r\n");
      out.write("        	let selecthall=$(\"#halls\").val();\r\n");
      out.write("        	$(\"#seat\").empty();\r\n");
      out.write("        	let soldSeats=[];\r\n");
      out.write("        	$.ajax({\r\n");
      out.write("                url: urlseat,\r\n");
      out.write("                data:{showtimeid:selecttime,hallid:selecthall},\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                success: function (respones) {\r\n");
      out.write("					$.each(respones,function(i,e){\r\n");
      out.write("						soldSeats.push(e.seatid);\r\n");
      out.write("					})\r\n");
      out.write("						let allSeats = [];\r\n");
      out.write("        // 生成所有座位 (假設 5 排，每排 5 個座位)\r\n");
      out.write("        for (let row of [\"A\", \"B\", \"C\", \"D\", \"E\"]) {\r\n");
      out.write("            for (let col = 1; col <= 10; col++) {\r\n");
      out.write("                allSeats.push(row + col);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        // 取得 <select> 元素\r\n");
      out.write("        let select = document.getElementById(\"seat\");\r\n");
      out.write("        // 過濾出尚未售出的座位\r\n");
      out.write("        let availableSeats = allSeats.filter(seat => !soldSeats.includes(seat));\r\n");
      out.write("        // 生成 <option> 並添加到 <select>\r\n");
      out.write("        availableSeats.forEach( function(seat) {\r\n");
      out.write("            //let option = document.createElement(\"option\");\r\n");
      out.write("            //option.value = seat;\r\n");
      out.write("           // option.textContent = seat;\r\n");
      out.write("            //select.appendChild(option);\r\n");
      out.write("            let seats='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.seatid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("            //console.log(seat)\r\n");
      out.write("            //console.log(urlhttp)\r\n");
      out.write("            //console.log(seats)\r\n");
      out.write("            let selectse = (seats == seat) ? 'selected':'';\r\n");
      out.write("            //console.log(selectse)\r\n");
      out.write("            //\r\n");
      out.write("            $('#seat').append(`<option value=\"${seat}\" ${selectse}>${seat}</option>`)\r\n");
      out.write("			\r\n");
      out.write("        })\r\n");
      out.write("            	},\r\n");
      out.write("            	error:function(){console.log('time')}\r\n");
      out.write("        	})\r\n");
      out.write("        })\r\n");
      out.write("        let money=[];\r\n");
      out.write("                let urltype = urlhttp+'findtype';\r\n");
      out.write("        console.log(urlhall)\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: urltype,\r\n");
      out.write("                    dataType: 'json',\r\n");
      out.write("                    type: 'GET',\r\n");
      out.write("                    success: function (respones) {\r\n");
      out.write("						$.each(respones,function(i,e){\r\n");
      out.write("							let ticktyp=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.tickettypeid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+1;/////////////////////////////////////\r\n");
      out.write("							\r\n");
      out.write("							//console.log(ticktyp)\r\n");
      out.write("							let se=e.tickettypeid\r\n");
      out.write("							let selectty=(ticktyp==se)?'selected':'';\r\n");
      out.write("							//console.log(ticktyp)\r\n");
      out.write("							//console.log(se)\r\n");
      out.write("							//console.log(selectty)\r\n");
      out.write("							$('#type').append(`<option value=\"${e.tickettypeid}\" ${selectty}>${e.tickettype}</option>`)\r\n");
      out.write("							money.push(e.moneytype)\r\n");
      out.write("							 let tp=	$('#type').val();\r\n");
      out.write("					        let time=$('#time').text();\r\n");
      out.write("					        //console.log(time)\r\n");
      out.write("					        let mf=0\r\n");
      out.write("					        	if(tp==1){\r\n");
      out.write("					        		\r\n");
      out.write("					        		mf=money[tp-1];\r\n");
      out.write("					        		$(\"#money\").val(mf)\r\n");
      out.write("					        	console.log()      \r\n");
      out.write("					        	}\r\n");
      out.write("					        	else if(tp==2){\r\n");
      out.write("					        		\r\n");
      out.write("					        		mf=money[tp-1];\r\n");
      out.write("					        		$(\"#money\").val(mf)\r\n");
      out.write("					            	}	\r\n");
      out.write("								else if(tp==3){\r\n");
      out.write("					        		\r\n");
      out.write("									mf=money[tp-1];\r\n");
      out.write("									$(\"#money\").val(mf)\r\n");
      out.write("					            	}else if(tp==4){\r\n");
      out.write("					            		\r\n");
      out.write("					            		mf=money[tp-1];\r\n");
      out.write("					            		$(\"#money\").val(mf)\r\n");
      out.write("					                	}\r\n");
      out.write("					})\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("    });\r\n");
      out.write("        $('#type').on(\"change\",function(){\r\n");
      out.write("        let tp=	$('#type').val();\r\n");
      out.write("        let time=$('#time').text();\r\n");
      out.write("        //console.log(time)\r\n");
      out.write("        let mf=0\r\n");
      out.write("        	if(tp==1){\r\n");
      out.write("        		\r\n");
      out.write("        		mf=money[tp-1];\r\n");
      out.write("        		$(\"#money\").val(mf)\r\n");
      out.write("        	console.log()      \r\n");
      out.write("        	}\r\n");
      out.write("        	else if(tp==2){\r\n");
      out.write("        		\r\n");
      out.write("        		mf=money[tp-1];\r\n");
      out.write("        		$(\"#money\").val(mf)\r\n");
      out.write("            	}	\r\n");
      out.write("			else if(tp==3){\r\n");
      out.write("        		\r\n");
      out.write("				mf=money[tp-1];\r\n");
      out.write("				$(\"#money\").val(mf)\r\n");
      out.write("            	}else if(tp==4){\r\n");
      out.write("            		\r\n");
      out.write("            		mf=money[tp-1];\r\n");
      out.write("            		$(\"#money\").val(mf)\r\n");
      out.write("                	}\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        $(\"#halls\").on(\"change\",function(){\r\n");
      out.write("        	$('#moviename').empty();\r\n");
      out.write("        	let hall=$(\"#halls\").val();\r\n");
      out.write("        	\r\n");
      out.write("        	urlname=urlhttp+\"findmoviename\"\r\n");
      out.write("        	$.ajax({\r\n");
      out.write("                url: urlname,\r\n");
      out.write("                data:{hallid:hall},\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                success: function (respones) {\r\n");
      out.write("                	\r\n");
      out.write("                		\r\n");
      out.write("                	$.each(respones,function(i,e){\r\n");
      out.write("                		//$('#moviename').append(`<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.movieid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.moviename}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>`)\r\n");
      out.write("						//$('#moviename').val(e.moviename)\r\n");
      out.write("						$('#moviename').append(`<option value=\"${e.movieid}\">${e.moviename}</option>`)\r\n");
      out.write("						\r\n");
      out.write("				})\r\n");
      out.write("					\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("        	\r\n");
      out.write("            \r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("    ////////////////////////////////////////////////\r\n");
      out.write("    });\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /proupdate/update.jsp(193,50) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.payout =='Y'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                        selected\r\n");
        out.write("                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /proupdate/update.jsp(196,50) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfo.payout =='N'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                        selected\r\n");
        out.write("                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
