/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-03-15 12:40:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.profind;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import com.tick.bean.BookticketBean;

public final class datatable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1741868033627L));
    _jspx_dependants.put("jar:file:/C:/Action/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664424678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tick.bean.BookticketBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\"\r\n");
      out.write("            integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\"\r\n");
      out.write("            crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("        <style>\r\n");
      out.write("        #bodddd {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            float: right;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #FFD700;\r\n");
      out.write("            background-color: #222;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("            margin-left: 10%;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li:hover {\r\n");
      out.write("            background-color: #FFCC00;\r\n");
      out.write("            color: #000;\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li i {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li:active {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 2px;\r\n");
      out.write("            background-color: #B22222;\r\n");
      out.write("            color: #FFF;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        figure {\r\n");
      out.write("            float: left;\r\n");
      out.write("            background-color: #000;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("            font-size: 100px;\r\n");
      out.write("            color: #FFD700;\r\n");
      out.write("            width: 10%;\r\n");
      out.write("            height: 1000px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .one {\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            padding-left: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: black;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li a:active {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 2px;\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .clock {\r\n");
      out.write("            color: #FFD700;\r\n");
      out.write("            font-size: 20%;\r\n");
      out.write("            letter-spacing: 7px;\r\n");
      out.write("            padding-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #new {\r\n");
      out.write("            font-size: 30px\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #new:hover {\r\n");
      out.write("            background-color: yellow;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #9fa19d;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("		.header {\r\n");
      out.write("		  font-family: \"Orbitron\", sans-serif;\r\n");
      out.write("		  font-optical-sizing: auto;\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("        .header {\r\n");
      out.write("        font-family: \"Orbitron\", sans-serif;\r\n");
      out.write("			border: 2px double #FFD700;\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            background: #000;\r\n");
      out.write("           color:#fff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-shadow:0.1em 0.1em 0.2em #fff;\r\n");
      out.write("         }\r\n");
      out.write("         .h1{\r\n");
      out.write("         \r\n");
      out.write("         text-shadow:0.1em 0.1em 0.2em gray;\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write(".myButton {\r\n");
      out.write("	box-shadow: 3px 4px 0px 0px #1564ad;\r\n");
      out.write("	background:linear-gradient(to bottom, #79bbff 5%, #378de5 100%);\r\n");
      out.write("	background-color:#79bbff;\r\n");
      out.write("	border-radius:5px;\r\n");
      out.write("	border:1px solid #337bc4;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	cursor:pointer;\r\n");
      out.write("	color:#ffffff;\r\n");
      out.write("	font-family:Arial;\r\n");
      out.write("	font-size:10px;\r\n");
      out.write("	font-weight:bold;\r\n");
      out.write("	padding:8.5px 29px;\r\n");
      out.write("	text-decoration:none;\r\n");
      out.write("	text-shadow:0px 0px 0px #528ecc;\r\n");
      out.write("}\r\n");
      out.write(".myButton:hover {\r\n");
      out.write("	background:linear-gradient(to bottom, #378de5 5%, #79bbff 100%);\r\n");
      out.write("	background-color:#378de5;\r\n");
      out.write("}\r\n");
      out.write(".myButton:active {\r\n");
      out.write("	position:relative;\r\n");
      out.write("	top:1px;\r\n");
      out.write("}\r\n");
      out.write("#new {\r\n");
      out.write("	box-shadow: 0px 10px 14px -7px #3e7327;\r\n");
      out.write("	background:linear-gradient(to bottom, #77b55a 5%, #72b352 100%);\r\n");
      out.write("	background-color:#77b55a;\r\n");
      out.write("	border-radius:4px;\r\n");
      out.write("	border:1px solid #4b8f29;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	cursor:pointer;\r\n");
      out.write("	color:#ffffff;\r\n");
      out.write("	font-family:Arial;\r\n");
      out.write("	font-size:22px;\r\n");
      out.write("	font-weight:bold;\r\n");
      out.write("	padding:6px 12px;\r\n");
      out.write("	text-decoration:none;\r\n");
      out.write("	text-shadow:0px 1px 0px #5b8a3c;\r\n");
      out.write("}\r\n");
      out.write("#new:hover {\r\n");
      out.write("	background:linear-gradient(to bottom, #72b352 5%, #77b55a 100%);\r\n");
      out.write("	background-color:#72b352;\r\n");
      out.write("}\r\n");
      out.write("#new:active {\r\n");
      out.write("	position:relative;\r\n");
      out.write("	top:1px;\r\n");
      out.write("}\r\n");
      out.write("#dell {\r\n");
      out.write("	box-shadow:inset 0px 1px 0px 0px #f5978e;\r\n");
      out.write("	background:linear-gradient(to bottom, #f24537 5%, #c62d1f 100%);\r\n");
      out.write("	background-color:#f24537;\r\n");
      out.write("	border-radius:6px;\r\n");
      out.write("	border:1px solid #d02718;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	cursor:pointer;\r\n");
      out.write("	color:#ffffff;\r\n");
      out.write("	font-family:Arial;\r\n");
      out.write("	font-size:15px;\r\n");
      out.write("	font-weight:bold;\r\n");
      out.write("	padding:6px 24px;\r\n");
      out.write("	text-decoration:none;\r\n");
      out.write("	text-shadow:0px 1px 0px #810e05;\r\n");
      out.write("}\r\n");
      out.write("#dell:hover {\r\n");
      out.write("	background:linear-gradient(to bottom, #c62d1f 5%, #f24537 100%);\r\n");
      out.write("	background-color:#c62d1f;\r\n");
      out.write("}\r\n");
      out.write("#dell:active {\r\n");
      out.write("	position:relative;\r\n");
      out.write("	top:1px;\r\n");
      out.write("}\r\n");
      out.write("#upda {\r\n");
      out.write("	box-shadow:inset 0px 1px 3px 0px #91b8b3;\r\n");
      out.write("	background:linear-gradient(to bottom, #768d87 5%, #6c7c7c 100%);\r\n");
      out.write("	background-color:#768d87;\r\n");
      out.write("	border-radius:5px;\r\n");
      out.write("	border:1px solid #566963;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	cursor:pointer;\r\n");
      out.write("	color:#ffffff;\r\n");
      out.write("	font-family:Arial;\r\n");
      out.write("	font-size:15px;\r\n");
      out.write("	font-weight:bold;\r\n");
      out.write("	padding:6px 24px;\r\n");
      out.write("	text-decoration:none;\r\n");
      out.write("	text-shadow:0px -1px 0px #2b665e;\r\n");
      out.write("}\r\n");
      out.write("#upda:hover {\r\n");
      out.write("	background:linear-gradient(to bottom, #6c7c7c 5%, #768d87 100%);\r\n");
      out.write("	background-color:#6c7c7c;\r\n");
      out.write("}\r\n");
      out.write("#upda:active {\r\n");
      out.write("	position:relative;\r\n");
      out.write("	top:1px;\r\n");
      out.write("}\r\n");
      out.write(".form-controlaa {\r\n");
      out.write("   \r\n");
      out.write("    width: 13%;\r\n");
      out.write("    height: 34px;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    line-height: 1.42857143;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    background-image: none;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);\r\n");
      out.write("    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);\r\n");
      out.write("    -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;\r\n");
      out.write("    -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;\r\n");
      out.write("    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;\r\n");
      out.write("}\r\n");
      out.write("#tise{\r\n");
      out.write("font-size:20px;\r\n");
      out.write("font-weight: 800\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  \r\n");
      out.write("  border : solid .1px black;\r\n");
      out.write("  border-radius: 35px;\r\n");
      out.write("  background-color :  #fff;\r\n");
      out.write("  \r\n");
      out.write("  outline:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("       \r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css\">\r\n");
      out.write("  		<!--link rel=\"stylesheet\" href=\"/resources/demos/style.css\"-->\r\n");
      out.write("  		  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.17.2/dist/sweetalert2.min.css\">\r\n");
      out.write("  		  <script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("  		<script src=\"https://code.jquery.com/ui/1.14.1/jquery-ui.js\"></script>\r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("        <title>訂票後台</title>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("     <div class=\"header\">光影之門後台系統MovieTicket</div>\r\n");
      out.write("        <figure>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <ul>\r\n");
      out.write("                <div id=\"MyClockDisplay\" class=\"clock\" onload=\"showTime()\"></div>\r\n");
      out.write("                <li class=\"one\"><i class=\"fa-solid fa-house\"></i></li>\r\n");
      out.write("                <!--  <li class=\"two\"><i class=\"fa-solid fa-ticket\"></i></li>-->\r\n");
      out.write("                <!-- <li class=\"three\"><i class=\"fa-solid fa-clock\"></i></li> -->\r\n");
      out.write("                <li class=\"fort\"><i class=\"fa-solid fa-film\"></i></li>\r\n");
      out.write("                <li class=\"five\"><i class=\"fa-solid fa-utensils\"></i></li>\r\n");
      out.write("                <li class=\"six\"><i class=\"fa-solid fa-bullhorn\"></i></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </figure>\r\n");
      out.write("        <!-- -------------------------------------------------------------------------------------------- -->\r\n");
      out.write("        <div id=\"selectfind\">\r\n");
      out.write("       \r\n");
      out.write("        <form action=\"findticketbyOther\">\r\n");
      out.write("         <span id=\"tise\">選擇你要查詢的內容</span>\r\n");
      out.write("        	<select id=\"findtick\" name=\"select\"	class=\"form-controlaa\">\r\n");
      out.write("            	<option value=\"\">選項</option>\r\n");
      out.write("            	<option value=\"1\">訂票ID</option>\r\n");
      out.write("            	<option value=\"2\">訂單編號</option>\r\n");
      out.write("            	<option value=\"3\">會員ID</option>\r\n");
      out.write("            	<option value=\"4\">日期</option>\r\n");
      out.write("            	<option value=\"5\">廳</option>\r\n");
      out.write("            	<option value=\"6\">電影名稱</option>\r\n");
      out.write("            	<option value=\"7\">是否付款</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            \r\n");
      out.write("            <button id=\"ok\" type=\"submit\" class=\"myButton\">送出</button>\r\n");
      out.write("            <a href=\"http://localhost:8080/project/findticketAll\" class=\"myButton\">查全部</a>\r\n");
      out.write("            <div id=\"fromfind\">\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"bodddd\">\r\n");
      out.write("        	\r\n");
      out.write("            <table id=\"myTable\" class=\"display\">\r\n");
      out.write("            \r\n");
      out.write("                <thead>\r\n");
      out.write("                \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>訂票ID</th>\r\n");
      out.write("                        <th>訂單編號</th>\r\n");
      out.write("                        <th>會員ID</th>\r\n");
      out.write("                        <th>日期</th>\r\n");
      out.write("                        <th>時間</th>\r\n");
      out.write("                        <th>座位</th>\r\n");
      out.write("                        <th>廳</th>\r\n");
      out.write("                        <th>單價</th>\r\n");
      out.write("                        <th>電影名稱</th>\r\n");
      out.write("                        <th>票種</th>\r\n");
      out.write("                        <th>是否付款</th>\r\n");
      out.write("                        <th>修改</th>\r\n");
      out.write("						<th>刪除</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("				");
 //List<BookticketBean> ticks =(ArrayList<BookticketBean>)request.getAttribute("tickinfo");
					//for(BookticketBean tickinfos:ticks){
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
//} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("		<a href=\"http://localhost:8080/project/proinser/inserform.html\" id=\"new\">新增</a>\r\n");
      out.write("        </div>\r\n");
      out.write("       	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.datatables.net/2.2.2/js/dataTables.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("        \r\n");
      out.write("            $(function () {\r\n");
      out.write("            	\r\n");
      out.write("            	$('.dellc').click(function(){\r\n");
      out.write("            	let idtick= $(this).data(\"value\")\r\n");
      out.write("            	\r\n");
      out.write("            		Swal.fire({\r\n");
      out.write("            		  title: \"你確定要刪除?\",\r\n");
      out.write("            		  text: \"資料會從這個世界上消失！\",\r\n");
      out.write("            		  icon: \"warning\",\r\n");
      out.write("            		  showCancelButton: true,\r\n");
      out.write("            		  confirmButtonColor: \"#3085d6\",\r\n");
      out.write("            		  cancelButtonColor: \"#d33\",\r\n");
      out.write("            		  confirmButtonText: \"是，這筆資料不重要!\"\r\n");
      out.write("            		}).then((result) => {\r\n");
      out.write("            		  if (result.isConfirmed) {\r\n");
      out.write("            		    Swal.fire({\r\n");
      out.write("            		      title: \"刪除成功!\",\r\n");
      out.write("            		      text: \"以已消失的無影無蹤了!!\",\r\n");
      out.write("            		      icon: \"success\"\r\n");
      out.write("            		    });\r\n");
      out.write("            		  // console.log(idtick)\r\n");
      out.write("            		  setTimeout(function() {\r\n");
      out.write("            		    window.location.href =\"http://localhost:8080/project/dele?tickid=\"+idtick\r\n");
      out.write("    		        	\r\n");
      out.write("    		          }, 2000);\r\n");
      out.write("            		  }\r\n");
      out.write("            		});\r\n");
      out.write("            	})\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	//////\r\n");
      out.write("            	let urlhttp='http://localhost:8080/project/';\r\n");
      out.write("            	///////////////////\r\n");
      out.write("                $(document).ready(function () {\r\n");
      out.write("                    $('#myTable').DataTable();\r\n");
      out.write("                })\r\n");
      out.write("/////////////////////////////////////////////////////////////\r\n");
      out.write("				$('#findtick').on(\"change\",function(){\r\n");
      out.write("					//console.log($('#findtick').val())\r\n");
      out.write("					 $('#fromfind').empty();\r\n");
      out.write("					 if($('#findtick').val()==1){\r\n");
      out.write("						console.log(1)\r\n");
      out.write("						//\r\n");
      out.write("						$('#fromfind').append(`<input placeholder=\"請輸入訂票ID\" name=\"tickid\">`)\r\n");
      out.write("					}else if($('#findtick').val()==2){\r\n");
      out.write("						console.log(2)\r\n");
      out.write("\r\n");
      out.write("						$('#fromfind').append(`<input placeholder=\"請輸入訂票編號\" name=\"orderid\">`)\r\n");
      out.write("					}else if($('#findtick').val()==3){\r\n");
      out.write("						console.log(3)\r\n");
      out.write("						$('#fromfind').append(`<input placeholder=\"請輸入會員ID\" name=\"userid\">`)\r\n");
      out.write("					}else if($('#findtick').val()==4){\r\n");
      out.write("						console.log(4)\r\n");
      out.write("						$('#fromfind').append(`<p><input type=\"date\" placeholder=\"請選擇日期\" name=\"startdate\" id=\"date1\"></p>`)\r\n");
      out.write("						\r\n");
      out.write("					}else if($('#findtick').val()==5){\r\n");
      out.write("						console.log(5)\r\n");
      out.write("						$('#fromfind').append(`<input placeholder=\"請輸入廳\" name=\"hallid\">`)\r\n");
      out.write("					}else if($('#findtick').val()==6){\r\n");
      out.write("						console.log(6)\r\n");
      out.write("						$('#fromfind').append(`<select id=\"selname\" name=\"findname\" class=\"form-controlaa\"></select>`)\r\n");
      out.write("						urlname=urlhttp+\"findmovienameall\"\r\n");
      out.write("						$.ajax({\r\n");
      out.write("                					url: urlname,\r\n");
      out.write("                					dataType: 'json',\r\n");
      out.write("                					type: 'GET',\r\n");
      out.write("                					success: function (respones) {\r\n");
      out.write("                	\r\n");
      out.write("                		\r\n");
      out.write("				                	$.each(respones,function(i,e){\r\n");
      out.write("				                		//$('#moviename').append(`<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.movieid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.moviename}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>`)\r\n");
      out.write("										//$('#moviename').val(e.moviename)\r\n");
      out.write("										$('#selname').append(`<option value=\"${e.movieid}\">${e.moviename}</option>`)\r\n");
      out.write("						\r\n");
      out.write("									})\r\n");
      out.write("										\r\n");
      out.write("					                }\r\n");
      out.write("           				 })\r\n");
      out.write("						\r\n");
      out.write("					}else if($('#findtick').val()==7){\r\n");
      out.write("						console.log(7)\r\n");
      out.write("						$('#fromfind').append(`<select name=\"payout\" class=\"form-controlaa\">\r\n");
      out.write("												<option value=\"Y\">已付</option>\r\n");
      out.write("												<option value=\"N\">未付</option>\r\n");
      out.write("											   </select>`)\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("				})\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("///////////////////////////////////////////////\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("                let elem = document.querySelectorAll(\"li\");\r\n");
      out.write("                elem.forEach(function (v) {\r\n");
      out.write("                    v.addEventListener('mouseenter', function () {\r\n");
      out.write("\r\n");
      out.write("                        if (v.classList == \"one\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<a href=\"http://localhost:8080/project/backEnd.view/HomePage.html\"><i class=\"fa-solid fa-house\"></i>會員</a>`\r\n");
      out.write("                        } else if (v.classList == \"two\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<a href=\"\"><i class=\"fa-solid fa-ticket\"></i>訂票</a>`\r\n");
      out.write("                        } else if (v.classList == \"three\") {\r\n");
      out.write("\r\n");
      out.write("                           // v.innerHTML = `<a href=\"https://www.youtube.com/\"><i class=\"fa-solid fa-clock\"></i>場次</a>`\r\n");
      out.write("                        } else if (v.classList == \"fort\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<a href=\"http://localhost:8080/project/JSP-zh/select.html\"><i class=\"fa-solid fa-film\"></i>電影</a>`\r\n");
      out.write("                        } else if (v.classList == \"five\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<a href=\"http://localhost:8080/project/hw2/menupage.html\"><i class=\"fa-solid fa-utensils\"></i>訂餐</a>`\r\n");
      out.write("                        } else if (v.classList == \"six\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<a href=\"http://localhost:8080/project/GetAllNews\"><i class=\"fa-solid fa-bullhorn\"></i>公告</a>`\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    })\r\n");
      out.write("\r\n");
      out.write("                    //滑鼠移出時恢復背景顏色\r\n");
      out.write("                    v.addEventListener('mouseleave', function () {\r\n");
      out.write("                        // this.style.fontSize = '';\r\n");
      out.write("                        if (v.classList == \"one\") {\r\n");
      out.write("                            console.log(\"aaa\");\r\n");
      out.write("                            v.innerHTML = `<i class=\"fa-solid fa-house\"></i>`\r\n");
      out.write("                        } if (v.classList == \"one\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<i class=\"fa-solid fa-house\"></i>  `\r\n");
      out.write("                        } else if (v.classList == \"two\") {\r\n");
      out.write("\r\n");
      out.write("                           // v.innerHTML = `<i class=\"fa-solid fa-ticket\"></i>  `\r\n");
      out.write("                        } else if (v.classList == \"three\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<i class=\"fa-solid fa-clock\"></i>  `\r\n");
      out.write("                        } else if (v.classList == \"fort\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<i class=\"fa-solid fa-film\"></i>  `\r\n");
      out.write("                        } else if (v.classList == \"five\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<i class=\"fa-solid fa-utensils\"></i>  `\r\n");
      out.write("                        } else if (v.classList == \"six\") {\r\n");
      out.write("\r\n");
      out.write("                            v.innerHTML = `<i class=\"fa-solid fa-bullhorn\"></i>  `\r\n");
      out.write("                        }\r\n");
      out.write("                    })\r\n");
      out.write("                })\r\n");
      out.write("                //滑鼠移入時改變背景顏色（藍）\r\n");
      out.write("\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            function showTime() {\r\n");
      out.write("                var date = new Date();\r\n");
      out.write("                var h = date.getHours(); // 0 - 23\r\n");
      out.write("                var m = date.getMinutes(); // 0 - 59\r\n");
      out.write("                var s = date.getSeconds(); // 0 - 59\r\n");
      out.write("                var session = \"AM\";\r\n");
      out.write("\r\n");
      out.write("                if (h == 0) {\r\n");
      out.write("                    h = 12;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (h > 12) {\r\n");
      out.write("                    h = h - 12;\r\n");
      out.write("                    session = \"PM\";\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                h = (h < 10) ? \"0\" + h : h;\r\n");
      out.write("                m = (m < 10) ? \"0\" + m : m;\r\n");
      out.write("                s = (s < 10) ? \"0\" + s : s;\r\n");
      out.write("\r\n");
      out.write("                var time = h + \":\" + m + \":\" + s + \" \" + session;\r\n");
      out.write("                document.getElementById(\"MyClockDisplay\").innerText = time;\r\n");
      out.write("                document.getElementById(\"MyClockDisplay\").textContent = time;\r\n");
      out.write("\r\n");
      out.write("                setTimeout(showTime, 1000);\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            showTime();\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /profind/datatable.jsp(354,5) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/profind/datatable.jsp(354,5) '${tickinfo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${tickinfo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /profind/datatable.jsp(354,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("tickinfos");
    // /profind/datatable.jsp(354,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("s");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <tr>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.tickid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.orderid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.userid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.startdate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.starttime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.seatid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.hallid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.onemoney}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.moviename}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.booktype}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.payout}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                        <td><a href=\"http://localhost:8080/project/Getupdateticketbyid?tickid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ tickinfos.tickid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"upda\">修改</a></td>\r\n");
          out.write("                        <td><a class=\"dellc\" id=\"dell\" data-value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tickinfos.tickid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">刪除</a></td>\r\n");
          out.write("                    </tr>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
